### ISSUE TITLE
Removes the import for the dart `meta` package

### ISSUE THREAD

**Issue by meta-boy** [Matt-Gleich/import_sorter#3]
when running the command, it removes the imports for https://pub.dev/packages/meta 

Way to reproduce:

```dart
import 'package:meta/meta.dart';

class PackageNotFound implements Exception {
  final String reason;
  PackageNotFound({@required this.reason});
}
``` 
example custom exception, within some file inside the working directory. Run the command 
```pub run import_sorter:main```

**Comment by Matt-Gleich** [comment]
👋 Hello! Thanks for using import_sorter!

1. What version of import_sorter are you running?
2. What does your pubspec.yaml look like?

Thanks!

**Comment by Matt-Gleich** [comment]
Upgrade the version to `^1.0.4` and you should be good. Just cloned your project and it worked for me. I'll close this issue once you let me know it works for you.

**Comment by meta-boy** [comment]
Yes it worked, thankyou
